/**
 *
 * Copyright (C) 2009-2014 INRA.
 * Copyright (C) 2009-2014 CETIOM.
 *
 *
 * TODO licence
 */


#ifndef SUNFLO_PHENOLOGIE_HPP
#define SUNFLO_PHENOLOGIE_HPP

namespace sunflo {

enum ValeurPhasePhenoPlante {
    PHASEPHENOPLANTE_NONSEMEE = 0,
    PHASEPHENOPLANTE_GERMINATION = 1,
    PHASEPHENOPLANTE_JUVENILE = 2,
    PHASEPHENOPLANTE_CROISSANCEACTIVE = 3,
    PHASEPHENOPLANTE_FLORAISON = 4,
    PHASEPHENOPLANTE_MATURATION = 5,
    PHASEPHENOPLANTE_DESSICATION = 6,
    PHASEPHENOPLANTE_RECOLTEE = 7
};

} // namespace

#endif
