# Carolina's functions <- function() {}
 <- function() {}
calc_LAI <- function() {}
calc_LAD <- function() {}
calc_MRUE <- function() {}
calc_STDM <- function() {}
calc_GY <- function() {}
calc_OC <- function() {}
calc_STDM_F <- function() {}
calc_SGR <- function() {}
calc_SIR <- function() {}
calc_SGR_EF <- function() {}
calc_SGR_FM <- function() {}
calc_SGR_MH <- function() {}
calc_SIR_EF <- function() {}
calc_SIR_FM <- function() {}
calc_SIR_MH <- function() {}
calc_SNAB <- function() {}
calc_SNNI <- function() {}
calc_SFNRUE <- function() {}
calc_SNAB_EF <- function() {}
calc_SNAB_FM <- function() {}
calc_SNAB_EM <- function() {}
calc_SNAB_MH <- function() {}
calc_NNI_F <- function() {}
calc_NNNID_EM <- function() {}
calc_NNNIE_EM <- function() {}
calc_SNNI_EF <- function() {}
calc_SNNI_FM <- function() {}
calc_SNNI_MH <- function() {}
calc_SFNRUE_EF <- function() {}
calc_SFNRUE_FM <- function() {}
calc_SFNRUE_MH <- function() {}
