# Jenna Functions

# From the parametrization_default file, indicators_metadata sheet
# Defining functions for factors temperature and water

calc_TT  <- function() {}
calc_D_SE <- function() {}
calc_D_EF <- function() {}
calc_D_FM <- function() {}
calc_D_MH <- function() {}
calc_NHT <- function() {}
calc_NLT <- function() {}
calc_SHT <- function() {}
calc_SLT <- function() {}
calc_SFTRUE <- function() {}
calc_TT_SE <- function() {}
calc_TT_EF <- function() {}
calc_TT_FM <- function() {}
calc_TT_MH <- function() {}
calc_SFTRUE_EF <- function() {}
calc_SFTRUE_FM <- function() {}
calc_SFTRUE_MH <- function() {}
calc_NLT_EF <- function() {}
calc_NLT_FM <- function() {}
calc_NLT_MH <- function() {}
calc_NHT_EF <- function() {}
calc_NHT_FM <- function() {}
calc_NHT_MH <- function() {}
calc_SLT_EF <- function() {}
calc_SLT_FM <- function() {}
calc_SLT_MH <- function() {}
calc_SHT_EF <- function() {}
calc_SHT_FM <- function() {}
calc_SHT_MH <- function() {}
calc_SRR <- function() {}
calc_SPET <- function() {}
calc_SCWD <- function() {}
calc_SFTSW <- function() {}
calc_MET <- function() {}
calc_NET <- function() {}
calc_SFHTR <- function() {}
calc_SFHRUE <- function() {}
calc_SRR_EF <- function() {}
calc_SRR_FM <- function() {}
calc_SRR_MH <- function() {}
calc_SPET_EF <- function() {}
calc_SPET_FM <- function() {}
calc_SPET_MH <- function() {}
calc_SCWD_EF <- function() {}
calc_SCWD_FM <- function() {}
calc_SCWD_MH <- function() {}
calc_MET_EF <- function() {}
calc_MET_FM <- function() {}
calc_MET_MH <- function() {}
calc_NET_EF <- function() {}
calc_NET_FM <- function() {}
calc_NET_MH <- function() {}
calc_SFTSW_EF <- function() {}
calc_SFTSW_FM <- function() {}
calc_SFTSW_MH <- function() {}
calc_SFHRUE_EF <- function() {}
calc_SFHRUE_FM <- function() {}
calc_SFHRUE_MH <- function() {}
calc_SFHTR_EF <- function() {}
calc_SFHTR_FM <- function() {}
calc_SFHTR_MH <- function() {}
