---
title: "Helianthus DESeq2"
author: "Carolina"
date: "2025-03-31"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load libraries 
library(dplyr)
library(tidyr)
library(tibble)
library(readr)
library(ggplot2)
library(purrr)
library(magrittr)
library(pheatmap)
library(textshape)
library(Rcpp)
library(matrixStats)
library(rtracklayer)
library(tidyverse)
library(DESeq2)
library(broom)
library(reshape)
```


## Counts and TPM data clean-up 
```{r sample raw data pre-processing}
## Upload raw data and set pvalue and log fold parameters for analyses
COUNTS_PATH      <- "data/salmon.merged.gene_counts.tsv"
TPM_PATH         <- "data/salmon.merged.gene_tpm.tsv"
FILTER_TRESHOLD  <- 0
P_VALUE_FILTER   <- 0.05
LOG2_FOLD_FILTER <- 1

## Read raw data and make dictionary mapping gene id with gene name
counts_orig  <- read.table(COUNTS_PATH, header=TRUE, row.names=1)
tpm_orig     <- read.table(TPM_PATH, header=TRUE, row.names=1)
g2s          <- data.frame(gene_id = rownames(counts_orig), 
                           gene_name = counts_orig[ , 1]) 
write.csv(g2s, "results/g2s.csv")

## Filter counts and tpm dataset to have only the data from the samples we want
# Load selected samples data
selected_samples <- read.csv("named_selected_all.csv", header = TRUE, stringsAsFactors = FALSE)

# Add a Dummy column for easier manipulation later
selected_samples <- selected_samples %>%
  mutate(Dummy = TRUE)

# Turn samples into wide format 
selected_samples_wide <- selected_samples %>%
  pivot_wider(names_from = V2, values_from = Dummy, values_fill = FALSE)

# Filter counts only from the samples that are in the selected_samples list
counts_selected <- counts_orig[, colnames(counts_orig) %in% colnames(selected_samples_wide)]

tpm_selected <- tpm_orig[, colnames(tpm_orig) %in% colnames(selected_samples_wide)]

## Convert counts to numerical rounded matrix
counts           <- counts_selected
tpm              <- tpm_selected
counts_matrix    <- as.matrix(counts) 
counts_matrix    <- round(counts_matrix)

# Filter genes with no counts for any of the samples
counts_filtered  <- counts_matrix[rowSums(counts_matrix) > FILTER_TRESHOLD, ]
tpm_filtered     <- tpm[rowSums(tpm) > FILTER_TRESHOLD, ]

save(counts, tpm, counts_filtered, tpm_filtered, g2s, file = "results/data_files.RData")

```

##DESeq2 Analysis for counts 
```{r make DESEQ2 metadata file and run DESEQ2}
# Make a column from the titles of the columns of the counts_matrix table
deseq_samples  <- data.frame(sample_id = colnames(counts))

# Split the sample names into strings to separate them from wild vs domesticated 
split_values <- strsplit(deseq_samples$sample_id, "_")
ecology_values <- sapply(split_values, function(x) x[[3]])

table(ecology_values)
# Add ecology values as columns to deseq_samples and factor them
deseq_samples$ecology <- ecology_values

#deseq_samples$ecology <- factor(deseq_samples$ecology, levels=c("domesticated","wild"))

# Prepare DESeq dataset and run DESea2
dds <- DESeqDataSetFromMatrix(countData = counts_filtered,
                              colData = deseq_samples,
                              design = ~ ecology) 

# See dds details
dds

# Remove gene counts that are low(less than 20 counts)
keep <- rowSums(counts(dds)) >=20
dds <- dds[keep,]

# See dds details again to see if we got rid of anything
dds

# Relevel factors and set domesticated as reference for analysis
dds$ecology <- relevel(dds$ecology, ref = "domesticated")

# Check levels were determined correctly
levels(dds$ecology)

# Run DESeq function
dds <- DESeq(dds)

# Save DESeq results in a variable 
res <- results(dds)
summary(res)

# Filter with a stricter threshold
res0.01 <- results(dds, alpha = 0.01)
summary(res0.01)

resultsNames(dds)

save(dds, res, deseq_samples, file = "results/DESeq2_data.RData")


```
### Obtaining and filtering count results wild vs domesticated 
```{r obtain count results for wild vs domesticated species and filter}
# Define the comparisons
comparison_list <- list(
  # Time points against baseline
  wild_vs_domesticated = c("ecology", "wild", "domesticated")
  )

# Create empty df to store results values (schema looks good)
results <- data.frame("gene_id" = character(),
                      "baseMean" = numeric(),
                      "log2FoldChange" = numeric(),
                      "lfcSE" = numeric(),
                      "stat" = numeric(),
                      "pvalue" = numeric(),
                      "padj" = numeric(),
                      "gene_name" = character(),
                      "comparison" = character())

# Loop through the defined contrasts
for(i in names(comparison_list)) {
  current_comparison <- comparison_list[[i]] # get comparison i
  res <- results(dds, contrast = current_comparison) # get results for time comparison i using 'contrast'
  if (is.null(res)) {
      warning(paste("Could not generate results for contrast:", i))
      next}
  # Temporary df to store the results for comparison i
  tmp_res_df <- res %>% 
    as.data.frame() %>%
    rownames_to_column("gene_id") %>%
    merge(g2s, by = "gene_id", all.x = TRUE) %>% 
    mutate(comparison = i) 
  # Add the temporary df to the main results df
  results <- bind_rows(results, tmp_res_df)
}

# Filter based on p-value < 0.05 and log2 fold change > 1. This data set includes the whole data for our filtered significant genes
filtered_results <- results %>%
  filter(padj < P_VALUE_FILTER, abs(log2FoldChange) > LOG2_FOLD_FILTER)

# Get all gene names that are significant and drop gene name repetitions. This data set will include only one column with all the significant genes
filtered_genes <- as.data.frame(filtered_results$gene_name, collapse = "\n")
filtered_genes <- unique(filtered_genes)
colnames(filtered_genes)[1] <- "gene_name"

write.table(filtered_genes["gene_name"], row.names = FALSE, col.names = FALSE, "results/filtered_genes.csv")

save(results, filtered_results, filtered_genes, file = "results/results_counts.RData")

```

### Obtaining tmp results
```{r calculate avg and sd for tpms}
# Create an ecology value and an empty list to calculate the std and avg values in our data 
ecology <- c("wild", "domesticated")
avg_and_sd_values <- list()

for (i in ecology) {
  cols     <- colnames(tpm_filtered)
  avg      <- rowMeans(tpm_filtered[, cols])
  sd       <- apply(tpm_filtered[, cols], 1, sd)
  sd       <- data.frame(sd)
  combined <- cbind(avg, sd)
  avg_and_sd_values <- c(avg_and_sd_values, list(combined))
}

# Convert the list to a data frame and add column names for the respective ecology
avg_and_sd_values           <- do.call(cbind,  avg_and_sd_values)
colnames(avg_and_sd_values) <- paste0(rep(ecology, each = 2), c("_avg", "_sd"))
avg_and_sd_values           <- as.data.frame(avg_and_sd_values) %>% rownames_to_column("gene_id") %>% merge(g2s)

save(avg_and_sd_values, file = "results/results_tpm.RData" )
```

### Distribution of count results
```{r filtered counts statistics distributions}

par(mfrow = c(1, 1))
# lfcSE histogram
hist(filtered_results$lfcSE, 
     main = "lfcSE", 
     xlab = "lfcSE", 
     xlim = c(0, 2), 
     breaks = 100, 
     col = "green", 
     border = "white")
# Adjusted p-value histogram
hist(filtered_results$padj, 
     main = "Adjusted P-value", 
     xlab = "padj", 
     xlim = c(0, P_VALUE_FILTER), 
     breaks = 50, 
     col = "purple", 
     border = "white")
# Log2 Fold Change histogram
hist(filtered_results$log2FoldChange, 
     main = "Log2 Fold Change", 
     xlab = "log2FoldChange", 
     xlim = c(-5, 5), 
     breaks = 1000, 
     col = "lightblue", 
     border = "white")

# T-test comparing baseMean expression of all genes vs filtered genes
basemean_all_genes <- median(results$baseMean)
basemean_fil_genes <- median(filtered_results$baseMean)
t.test(results$baseMean, filtered_results$baseMean)

# Intersect by gene_name filtered results table and raw counts
counts_filtered_genes <- counts_selected[filtered_results$gene_id,]
```


